name: MLOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  setup-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9.13'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_KEY_JSON }}'

    - name: Set GCP Project ID
      run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Run Data Pipeline
      run: |
        python scripts/setup_gcloud.py
        python scripts/download_data.py
        python scripts/upload_to_bucket.py
